#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          64

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#519f50"
bspc config normal_border_color "#1c1b19"

sxhkd -c $HOME/.config/sxhkd/sxhkdrc $HOME/.config/sxhkd/bsrc &

polybar -c $HOME/.config/polybar/bspwm-config bspwm &

