# Monitor 1

[[appRule]]
title = "nuclearthrone"
monitor = 1
tags = [ 9 ]
state = "fullscreen"

[[appRule]]
instance = "nuclearthronetogether.exe"
state = "fullscreen"

[[appRule]]
instance = "riotclientux.exe"
monitor = 1
tags = [ 9 ]

[[appRule]]
instance = "leagueclient.exe"
monitor = 1
tags = [ 9 ]

[[appRule]]
instance = "league of legends.exe"
monitor = 1
tags = [ 9 ]

[[appRule]]
instance = "leagueclientux.exe"
monitor = 1
tags = [ 9 ]

# Monitor 2

[[appRule]]
class = "weechat"
monitor = 2
tags = [ 1 ]

[[appRule]]
class = "util-term"
monitor = 2
tags = [ 1 ]

[[appRule]]
class = "discord"
monitor = 2
tags = [ 1 ]

[[appRule]]
class = "element-desktop"
monitor = 2
tags = [ 1 ]

# Start external programs

[[startProcess]]
command = "win=$(xdotool getactivewindow) && xdotool key --window $win super+space; xdotool windowsize $win 800 970;  xdotool windowmove $win 560 295"
keys = [ "c" ]
modifiers = [ "super" ]

[autostart]
exec = [
  "xsetroot -cursor_name left_ptr",
  "~/.config/nimdow/autostart.sh"
]

[settings]
  # Window settings
  windowTitlePosition = "left"
  gapSize = 24
  borderWidth = 1
  borderColorFocused = "#50fa7b"
  borderColorUnfocused = "#282a36"
  # Bar settings
  barHeight = 20
  barBackgroundColor = "#282a36"
  barForegroundColor = "#f8f8f2"
  barSelectionColor = "#50fa7b"
  barUrgentColor = "#ff5555"
  barFonts = [
    "monospace:size=10:antialias=true",
    "NotoColorEmoji:size=10:antialias=true"
    "Source Han Sans TC,思源黑體:size=10:style=Regular:antialias=true"
  ]
  # General settings
  loggingEnabled = true

# Window manager controls
[controls]
  [controls.reloadConfig]
  keys = [ "r" ]
  modifiers = [ "super", "shift" ]

  [controls.focusPrevious]
  keys = [ "k" ]
  modifiers = [ "super" ]

  [controls.focusNext]
  keys = [ "j" ]
  modifiers = [ "super" ]

  [controls.moveWindowPrevious]
  keys = [ "k" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowNext]
  keys = [ "j" ]
  modifiers = [ "super", "shift" ]

  [controls.toggleFullscreen]
  keys = [ "f" ]
  modifiers = [ "super" ]

  [controls.destroySelectedWindow]
  keys = [ "q" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowToTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "shift" ]

  [controls.goToTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super" ]

  [controls.goToPreviousTag]
  keys = [ "w" ]
  modifiers = [ "super" ]

  [controls.toggleTagView]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "control" ]

  [controls.toggleWindowTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "shift", "control" ]

  [controls.focusPreviousMonitor]
  keys = [ "comma" ]
  modifiers = [ "super" ]

  [controls.focusNextMonitor]
  keys = [ "period" ]
  modifiers = [ "super" ]

  [controls.moveWindowToPreviousMonitor]
  keys = [ "comma" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowToNextMonitor]
  keys = [ "period" ]
  modifiers = [ "super", "shift" ]

  [controls.increaseMasterCount]
  keys = [ "z" ]
  modifiers = [ "super" ]

  [controls.decreaseMasterCount]
  keys = [ "x" ]
  modifiers = [ "super" ]

  [controls.toggleFloating]
  keys = [ "space" ]
  modifiers = [ "super" ]

  [controls.jumpToUrgentWindow]
  keys = [ "u" ]
  modifiers = [ "super" ]

  [controls.increaseMasterWidth]
  keys = [ "l" ]
  modifiers = [ "super" ]

  [controls.decreaseMasterWidth]
  keys = [ "h" ]
  modifiers = [ "super" ]

  [controls.moveWindowToScratchpad]
  keys = [ "s" ]
  modifiers = [ "super", "shift" ]

  [controls.popScratchpad]
  keys = [ "s" ]
  modifiers = [ "super" ]

[monitors]
  [monitors.2.tags]
  1.numMasterWindows = 2

