[[startProcess]]
command = "notify-send \"region 1\""
clickRegion = 1

[[startProcess]]
command = "notify-send \"region 2\""
clickRegion = 2

[[startProcess]]
command = "notify-send \"region 3\""
clickRegion = 3


# Monitor 1
[[appRule]]
class = "pentablet"
state = "floating"

[[appRule]]
title = "nuclearthrone"
monitor = 1
tags = [ 9 ]
state = "fullscreen"

[[appRule]]
instance = "nuclearthronetogether.exe"
state = "fullscreen"

[[appRule]]
instance = "riotclientux.exe"
monitor = 1
tags = [ 9 ]

[[appRule]]
instance = "leagueclient.exe"
monitor = 1
tags = [ 9 ]

[[appRule]]
instance = "league of legends.exe"
monitor = 1
tags = [ 9 ]
state = "fullscreen"

[[appRule]]
instance = "leagueclientux.exe"
monitor = 1
tags = [ 9 ]

[[appRule]]
title = "League of Legends"
monitor = 1
tags = [ 9 ]

[[appRule]]
class = "Lutris"
monitor = 1
tags = [ 8 ]

[[appRule]]
instance = "Steam"
monitor = 1
tags = [ 8 ]

[[appRule]]
title = "Apex Legends"
monitor = 1
tags = [ 9 ]

# Monitor 2

[[appRule]]
class = "discord"
monitor = 2
tags = [ 1 ]

[[appRule]]
class = "element-desktop"
monitor = 2
tags = [ 1 ]

[[appRule]]
title = "RuneLite Launcher"
state = "floating"

## Monitor agnostic

[[appRule]]
class = "Xephyr"
state = "fullscreen"

# Start external programs

[[startProcess]]
command = "win=$(xdotool getactivewindow) && xdotool key --window $win super+space; xdotool windowsize $win 800 970;  xdotool windowmove $win 560 295"
keys = [ "c" ]
modifiers = [ "super" ]

[[startProcess]]
command = "notify-send 'boop'"
keys = [ "q" ]
modifiers = [ "super" ]

[[startProcess]]
command = "light -A 1.25"
keys = [ "XF86MonBrightnessUp" ]

[[startProcess]]
command = "light -U 1.25"
keys = [ "XF86MonBrightnessDown" ]

[[startProcess]]
command = "notify-send 'print'"
keys = [ "Print" ]

[autostart]
exec = [
  "xsetroot -cursor_name left_ptr",
  "~/.config/nimdow/autostart.sh",
  "nm-applet"
]

[settings]
  # Window settings
  windowTitlePosition = "left"
  gapSize = 24
  borderWidth = 1
  borderColorUnfocused = "#282a36"
  borderColorFocused = "#50fa7b"
  borderColorUrgent = "#ff5555"
  # Bar settings
  barHeight = 20

  barBackgroundColor = "#282a36"
  barForegroundColor = "#f8f8f2"
  barSelectionColor = "#50fa7b"
  barUrgentColor = "#ff5555"
  barFonts = [
    "monospace:size=10:antialias=true",
    "monospace:size=14:antialias=true",
    "Font Awesome 5 Free Regular:style=Regular:size=10:antialias=true",
    "NotoColorEmoji:size=10:antialias=true"
    "Source Han Sans TC,思源黑體:size=10:style=Regular:antialias=true"
  ]
  # Scratchpad settings
  scratchpadWidth = 800
  scratchpadHeight = 600
  # General settings
  loggingEnabled = false
  reverseTagScrolling = false

# Window manager controls
[controls]
  [controls.reloadConfig]
  keys = [ "r" ]
  modifiers = [ "super", "shift" ]

  [controls.focusPrevious]
  keys = [ "k" ]
  modifiers = [ "super" ]

  [controls.focusNext]
  keys = [ "j" ]
  modifiers = [ "super" ]

  [controls.moveWindowPrevious]
  keys = [ "k" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowNext]
  keys = [ "j" ]
  modifiers = [ "super", "shift" ]

  [controls.toggleFullscreen]
  keys = [ "f" ]
  modifiers = [ "super" ]

  [controls.destroySelectedWindow]
  keys = [ "q" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowToTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "shift" ]

  [controls.goToTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super" ]

  [controls.goToPreviousTag]
  keys = [ "w" ]
  modifiers = [ "super" ]

  [controls.toggleTagView]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "control" ]

  [controls.toggleWindowTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "shift", "control" ]

  [controls.focusPreviousMonitor]
  keys = [ "comma" ]
  modifiers = [ "super" ]

  [controls.focusNextMonitor]
  keys = [ "period" ]
  modifiers = [ "super" ]

  [controls.moveWindowToPreviousMonitor]
  keys = [ "comma" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowToNextMonitor]
  keys = [ "period" ]
  modifiers = [ "super", "shift" ]

  [controls.increaseMasterCount]
  keys = [ "z" ]
  modifiers = [ "super" ]

  [controls.decreaseMasterCount]
  keys = [ "x" ]
  modifiers = [ "super" ]

  [controls.toggleFloating]
  keys = [ "space" ]
  modifiers = [ "super" ]

  [controls.jumpToUrgentWindow]
  keys = [ "u" ]
  modifiers = [ "super" ]

  [controls.increaseMasterWidth]
  keys = [ "l" ]
  modifiers = [ "super" ]

  [controls.decreaseMasterWidth]
  keys = [ "h" ]
  modifiers = [ "super" ]

  [controls.moveWindowToScratchpad]
  keys = [ "s" ]
  modifiers = [ "super", "shift" ]

  [controls.popScratchpad]
  keys = [ "s" ]
  modifiers = [ "super" ]

  [controls.rotateClients]
  keys = [ "r" ]
  modifiers = [ "super" ]

