background {
  monitor = # monitor-agnostic
  path = ~/.dotfiles/lock-wallpaper
  blur_passes = 3
  blur_size = 1
}

input-field {
  monitor =
  size = 8%, 3%
  font_family = Jetbrains Mono
  dots_size = 0.5

  outline_thickness = 3
  inner_color = rgba(0, 0, 0, 0.0) # no fill

  outer_color = rgba(0, 0, 0, 0.0)
  check_color=rgba(00ff99ee) rgba(ff6633ee) 120deg
  fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg

  font_color = rgb(143, 143, 143)
  fade_on_empty = true
  rounding = 0

  position = 0, -200
  halign = center
  valign = center
}

label {
  monitor =
  text = $TIME
  font_size = 100
  position = 0, -80
}
