#!/usr/bin/env sh

chosen=$(cat $HOME/.dotfiles/emoji.list | dmenu -i -l 20 -fn Monospace-14)

[ -n "$chosen" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | xclip -selection clipboard

s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
echo "$s" | tr -d '\n' | xclip

