#!/bin/bash

# Set the overall status
get_status() {
    battery_status="";
    if has_battery; then
        battery_status=" $(get_battery_status) |";
    fi

    reminder_count="$(remind list | wc -l)"
    upcoming_reminders=""
    if [ "$reminder_count" -gt 0 ]; then
      upcoming_reminders="Upcoming reminders: ${reminder_count} | "
    fi

    weather="$(cat "$HOME/.weather")"
    echo "${upcoming_reminders}$(get_dunst_status) | ${weather} |${battery_status} $(get_volume) | $(get_datetime)";
}

get_net_info() {
    info="$(nmcli)"
    device="$(echo "$info" | pcregrep -o1 -i "connected to (.*)")"
    if [[ -n "$device" ]]; then
        type="$(echo "$info" | awk 'NR==3 { print $1 }')"
        printf "%s: %s" "$type" "$device"
    fi
}

get_volume() {
    vol="$(pamixer --get-volume-human)"
    if [[ "$vol" == "muted" ]]; then
        printf "🔇 %s" "$vol"
    else
        printf "🔊 %s" "$vol"
    fi
}

get_datetime() {
    date +"📅 %a %d %b %Y | 🕓 %I:%M %p %Z"
}

# Battery

battery="BAT0";

has_battery() {
    if [ -d /sys/class/power_supply/$battery ]; then
        return 0;
    fi
    return 1;
}

get_battery_status() {
    charge="$(get_charge)"
    icon=""
    if [[ "$charge" -le 10 ]]; then
        icon="󰁺"
    elif [[ "$charge" -le 20 ]]; then
        icon="󰁻"
    elif [[ "$charge" -le 30 ]]; then
        icon="󰁼" 
    elif [[ "$charge" -le 40 ]]; then
        icon="󰁽" 
    elif [[ "$charge" -le 50 ]]; then
        icon="󰁾" 
    elif [[ "$charge" -le 60 ]]; then
        icon="󰁿" 
    elif [[ "$charge" -le 70 ]]; then
        icon="󰂀" 
    elif [[ "$charge" -le 80 ]]; then
        icon="󰂁" 
    elif [[ "$charge" -le 90 ]]; then
        icon="󰂂" 
    elif [[ "$charge" -le 100 ]]; then
        if [[ "$(get_charging_status)" == "Discharging" ]]; then
            icon="󰁹"
        else
            icon="󰂄" 
        fi
    else
        icon="󰂑"
    fi
    echo ""$icon" "$charge"%"
}

get_charging_status() {
    cat "/sys/class/power_supply/$battery/status"
}

get_charge() {
    cat "/sys/class/power_supply/$battery/capacity"
}

get_num_updates() {
  updates="$(checkupdates | wc -l)"
  if [ "$updates" -gt 0 ]; then
    echo "Updates: $updates |"
  fi
}

get_dunst_status() {
    COUNT=$(dunstctl count waiting)
    ENABLED=🔔
    DISABLED=🔕

    if [ "$COUNT" != 0 ]; then 
      DISABLED="🔕 $COUNT";
    fi

    if dunstctl is-paused | grep -q "false" ; then
      echo -e "\x1F$ENABLED\x1F";
    else
      echo -e "\x1F$DISABLED\x1F";
    fi
}

# Set the status bar

while true
do
    xsetroot -name "$(get_status)";
    sleep 1s;
done

