#!/usr/bin/env bash

current="$(cat "$HOME/.config/redshift/gamma")"

if [ -n "$current" ]; then
    redshift -x
    : > "$HOME/.config/redshift/gamma"
else
    red="4000"
    redshift -P -O "$red"
    mkdir -p "$HOME/.config/redshift/"
    echo "$red" > "$HOME/.config/redshift/gamma"
fi

