#!/bin/bash

current="$(cat "$HOME/.config/redshift/gamma")"

if [ -n "$current" ]; then
    redshift -x
    : > "$HOME/.config/redshift/gamma"
else
    red="5000"
    redshift -P -O "$red"
    echo "$red" > "$HOME/.config/redshift/gamma"
fi

