#!/usr/bin/env bash

# If first arg is --full, take full-screen immediately; otherwise interactive selection.
FULL=0
if [[ $1 == "--full" ]]; then
  FULL=1
fi

tmpfile=$(mktemp -t XXXXXX.png)

if [[ $FULL -eq 1 ]]; then
  maim -u "$tmpfile" || exit
else
  maim -sou > "$tmpfile" || exit
fi

action=$(printf "copy\nupload\nsave" | dmenu)

upload() {
  image="$1"
  url="$(
    curl \
      -s -L -X POST 'https://api.imgur.com/3/image' \
      -H 'Authorization: Client-ID 9e2d6e63b369a4d' -F "image=@$image" | \
      grep -o 'https.*\.png' | tr -d "\\"
    )"
  echo "$url"
}

case "$action" in
  copy)
    # webpfile="$(mktemp -t XXXXXX.webp)"
    # convert "$tmpfile" -strip -quality 70 "$webpfile" || exit
    # xclip -selection clipboard -t image/webp -i "$webpfile" \
    #     && notify-send "Saved image to clipboard"
    #
    # rm -f "$webpfile"

    xclip -selection clipboard -t image/png "$tmpfile" &&
      notify-send "Saved image to clipboard"
    ;;
  upload)
    upload "$tmpfile" | xclip -sel clipboard &&
      notify-send "Image link saved to clipboard"
    ;;
  save)
    destfile="$(zenity --file-selection --title="Save image" --save)"
    if [[ -n $destfile ]]; then
      mv "$tmpfile" "$destfile"
      notify-send "File saved to $destfile"
    fi
    ;;
  *)
    notify-send "Invalid action: $action"
    ;;
esac

rm "$tmpfile"

