#!/bin/bash

interval="$1"
if [ -z "$interval" ]; then
    echo "Please input a delay interval to query new weather info."
    exit 1
fi

while [ true ];
do
    mkdir -p $HOME/.config/weather/
    current="$(weather -i -r)"
    if [ -z "$current" ]; then
        sleep 1s
        continue
    else
        weather -i -r > "$HOME/.config/weather/current"
        sleep "$interval"
    fi
done

