#!/bin/bash

if [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]; then
    printf "Help Menu:\n\n"

    printf "      Help menu:              [-h | --help ]\n"
    printf "      Display with icon:      [-i | --icon ]\n"
    printf "      Round the temperature:  [-r | --round]\n"
    exit
fi

function get_icon() {
    weather_line="$1";
    if [[ "$weather_line" = *Snow* ]]; then
        echo "${ICON_SNOW}"
    elif [[ "$weather_line" = *Rain* ]] || [[ "$weather_line" = *Drizzle* ]]; then
        echo "${ICON_RAINY}"
    elif [[ "$weather_line" = *Cloud* ]]; then
        echo "${ICON_CLOUDY}"
    elif [[ "$weather_line" = *Clear* ]]; then
        echo "${ICON_SUNNY}"
    elif [[ "$weather_line" = *Fog* ]] || [[ "$weather_line" = *Mist* ]]; then
        echo "${ICON_FOG}"
    fi
}

API_KEY="730d0819cbc5feae20f1a2271c73752e"

# Check on http://openweathermap.org/find
CITY_ID="4465507"

ICON_SUNNY="🌞"
ICON_CLOUDY="⛅"
ICON_RAINY="🌧"
ICON_STORM="🌩"
ICON_SNOW="❄"
ICON_FOG="🌁"

SYMBOL_FARENHEIT="˚F"

WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=imperial"
WEATHER_RAW=$(wget -qO- "${WEATHER_URL}")
if [[ -z "${WEATHER_RAW}" ]]; then
    exit 1
fi

WEATHER_INFO=$(echo "${WEATHER_RAW}" | jq '.weather[0]')
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | jq '.main' | tr -d '"')
WEATHER_DESCRIPTION=$(echo "${WEATHER_INFO}" | jq '.description' | tr -d '"' | sed 's/./\U&/')
WEATHER_TEMP=$(echo "${WEATHER_RAW}" | jq '.main.temp')

current_icon=""

for arg in "$@"; do
    if [[ $arg == "-i" ]] || [[ $arg == "--icon" ]]; then
        current_icon="$(get_icon "$WEATHER_MAIN") " 
    elif [[ $arg == "-r" ]] || [[ $arg == "--round" ]]; then
        WEATHER_TEMP="$(LC_ALL=C /usr/bin/printf "%.*f\n" "0" "$WEATHER_TEMP")"
    fi
done

echo "${current_icon}${WEATHER_DESCRIPTION} ${WEATHER_TEMP}${SYMBOL_FARENHEIT}" 

