#!/usr/bin/env bash

interval="$1"
if [ -z "$interval" ]; then
    echo "Please input a delay interval to query new weather info."
    exit 1
fi

while true;
do
    current="$(weather -i -r)"
    if [ -z "$current" ]; then
        sleep 1s
        continue
    else
        echo "$current" > "$HOME/.weather"
        # refresh_nimdowstatus
        sleep "$interval"
    fi
done

