#!/usr/bin/env bash

interval="$1"
if [ -z "$interval" ]; then
    echo "Please input a delay interval to query new weather info."
    exit 1
fi

while true;
do
    mkdir -p "$HOME/.config/weather/"
    current="$(weather -i -r)"
    if [ -z "$current" ]; then
        sleep 5s
        continue
    else
        echo "$current" > "$HOME/.config/weather/current"
        refresh_nimdowstatus
        sleep "$interval"
    fi
done

