#!/usr/bin/env bash

msg=$1
cmd=$2

if [[ -z "$msg" ]] || [[ -z "$cmd" ]]; then
    printf "Invalid input - exiting.\n"
    exit 1;
fi

response=$(echo -e "no\nyes" | dmenu -l 2 -p "${msg}");

if [ "${response}" == "yes" ]; then
    sh -c "${cmd}"
fi

    
